version: '3.1'

services:

  redmine:
    build:
      context: ./redmine
    restart: always
    # 프록시 서버가 사용될 예정
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - /data:/data
      - ./volumes/files:/usr/src/redmine/files
      - ./volumes/plugins:/usr/src/redmine/plugins
      - ./volumes/themes:/usr/src/redmine/public/themes
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
